### ISSUE TITLE
Windows-specific problems

### ISSUE THREAD

**Issue by schungx** [rhaiscript/lsp#59]
Right now, if I put the following into `static.d.rhai`, it won't be allowed:

![image](https://user-images.githubusercontent.com/661318/178866905-dc10f553-41e3-44ea-924b-a65f7d79254e.png)

as operators are not allowed as function names in function declarations.

There are two solutions to this:

1) Allow symbols as function names; this is easiest but of course it breaks with "normal" Rhai code, but it shouldn't matter a great deal because they are already different (for example no function body).

```rust
fn ==(x: i64, y: i64) -> bool;
```

2) Use another keyword, for example

```rust
op ==(x: i64, y: i64) -> bool;

op x:i64 == y:i64 -> bool;
```

**Comment by tamasfe** [comment]
Yeah sorry, I removed it from the examples, the following is valid in syntax declarations, but are not processed further:

![image](https://user-images.githubusercontent.com/25967296/178867392-dddea4ad-c3d3-45cd-a03d-e3b5600356ff.png)

**Comment by tamasfe** [comment]
I forgot to change `:` to ``->`` to align with the function syntax.

**Comment by schungx** [comment]
BTW, just found out the following strangeness:

### No syntax errors:

![image](https://user-images.githubusercontent.com/661318/178867735-5e8e4484-9a1f-40af-98a6-0e2c02d1270e.png)

### Just one small syntax error:

![image](https://user-images.githubusercontent.com/661318/178867758-632fc759-49b9-4d6e-86d2-bee4fcd7c839.png)

As you can see, with any syntax error, built-in functions are not recognized.

**Comment by schungx** [comment]
The parser seems to recover gracefully by parsing the `for` statement as a new statement, but some internal state is probably thinking it is invalid.

**Comment by tamasfe** [comment]
I don't think that parse tree looks what it should like, can you paste the code so I can check it out?

**Comment by schungx** [comment]
It is `for1.rhai` in example scripts.  I believe you have it in the examples dir.

**Comment by schungx** [comment]
How should I help you track it down?

**Comment by schungx** [comment]
Hhmmm....  I just quit vscode and opened the file again.  This time it is different:

![image](https://user-images.githubusercontent.com/661318/178950867-9241075c-e5e2-4b3b-ab6c-8bf33365ea07.png)

Notice that the `for` keywords is not highlighted as syntax error.

**Comment by schungx** [comment]
> Can you check if there is anything in the logs? There should not even be any HIR errors if there are syntax errors.

I checked.  Nothing.  Only a whole bunch of lines saying "using external file xxxxx.rhai" or something like that.

**Comment by tamasfe** [comment]
That might be it, well, at least it is an issue if you don't have a folder opened.

If it's just a single file open in a vscode window, or a file that is not in the opened folder, it's expected, otherwise it's an issue as the document should be part of a workspace. Whether that is a cause of the error behaviour is unclear.

**Comment by schungx** [comment]
Clicking on `while.rhai` does this:

![image](https://user-images.githubusercontent.com/661318/178955322-15500e35-0078-44cb-a828-cfb29a99029a.png)

Clicking on `static.d.rhai` once, then open `while.rhai` again:

![image](https://user-images.githubusercontent.com/661318/178955407-a9d618d9-0edb-4519-9a88-2e520bf746e3.png)

**Comment by tamasfe** [comment]
Ah yeah. It's a windows specific issue, we'll have to look into how to handle absolute paths correctly.

On unix-like systems all file paths are quite simple, workspaces look like `/some/nested/directory`, while the path of a file in that workspace looks like `/some/nested/directory/example.rhai`, it is trivial to check whether a file is part of a workspace via simply a prefix check.

It is not as simple under windows, because:
- URLs require extra care due to percent encoding (having `c:` is not a valid in an URL)
- files and directories can be case-insensitive (although normally should not be an issue)
- the path separator can be either `\` or `/`

We'll probably have to "normalize" windows paths in some way in the LSP to account for these issues.

**Comment by schungx** [comment]
Ah.  So this is a Windows-related issue afterall.

I agree, path processing in Windows is a royal pain.  Usually you need to use [`File::canonicalize`](https://doc.rust-lang.org/std/fs/fn.canonicalize.html) to make a canonical pathname - this one works fine, I remember.

**Comment by tamasfe** [comment]
Yeah I see it now, that's one problem, I'll open an issue for that separately. Whether that fixes this remains to be seen.

**Comment by schungx** [comment]
Oops sorry, I believe canonical returns the UNC standard path format which is like `\\?\c\Git\rhai`

The `file:///c:/Git/rhai` format is the URI format, but I believe there are ways to translate between the two.

I'd suggest keeping to the URI format, which should work on both Windows and Unix.

**Comment by schungx** [comment]
Confirmed that the path issue is resolved.
